# Generated by Django 5.0.1 on 2024-01-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcard", "0003_flashcarddesafio_desafio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcarddesafio",
            name="flashcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flashcard.flashcard"
            ),
        ),
    ]
